theme: jekyll-theme-cayman
title: Are Housing Prices in University Towns Less Affected by Recessions?
description: Based on the assignments from Applied Plotting, Charting & Data Representation in Python by University of Michigan on Coursera
