theme: jekyll-theme-cayman
title: Weather Patterns in Silicon Valley
description: Based on assignments from Applied Plotting, Charting & Data Representation in Python by University of Michigan on Coursera
